"""BlenderTools-owned export snapshots; no Blender or game-file dependencies."""
import json
import re
import shutil
import uuid
import tempfile
import hashlib
from pathlib import Path
from datetime import datetime, timezone


def scan(directory):
    """Read immediate mod directories, never execute their Lua."""
    root = Path(directory)
    result = []
    if not root.is_dir():
        return result
    for folder in sorted(root.iterdir(), key=lambda p: p.name.casefold()):
        if not folder.is_dir() or folder.is_symlink():
            continue
        project = folder / 'project.json'
        metadata = folder / 'mod.json'
        if not project.is_file() and not metadata.is_file():
            continue
        row = dict(path=str(folder.resolve()), name=folder.name, project='', entries=[], error='', adoptable=False)
        try:
            if project.is_file():
                data = load(project)
                row.update(name=data['name'], project=str(project.resolve()), entries=data['entries'])
            else:
                data = json.loads(metadata.read_text(encoding='utf-8-sig'))
                row['name'] = data.get('name', folder.name)
                script = folder / 'src' / 'mod.lua'
                if script.is_file() and (folder / 'validation.json').is_file() and (folder / 'render_data.bin').is_file():
                    with script.open(encoding='utf-8-sig') as stream:
                        row['adoptable'] = 'Generated by Enshrouded Blender Tools' in stream.read(512)
        except (OSError, ValueError, KeyError, TypeError) as exc:
            row['error'] = str(exc)
        result.append(row)
    return result


def load(path):
    path = Path(path).resolve()
    data = json.loads(path.read_text(encoding='utf-8'))
    if data.get('format') != 'EBT_MOD_PROJECT_1':
        raise ValueError('Not a BlenderTools mod project')
    if not re.fullmatch(r'[a-z0-9][a-z0-9_-]*', data['id']):
        raise ValueError('Invalid project mod ID')
    for entry in data['entries']:
        uuid.UUID(hex=entry['id'])
        if not re.fullmatch('[a-f0-9]{32}', entry['snapshot']):
            raise ValueError('Invalid snapshot path')
    return data


def save(path, data):
    path = Path(path)
    temporary = path.with_suffix('.tmp')
    temporary.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding='utf-8')
    temporary.replace(path)


def create(directory, mod_id, name, version, author):
    if not re.fullmatch(r'[a-z0-9][a-z0-9_-]*', mod_id):
        raise ValueError('Use lowercase letters, numbers, _ or - for Mod ID')
    root = Path(directory).resolve() / mod_id
    root.mkdir(parents=True, exist_ok=False)
    path = root / 'project.json'
    save(path, dict(format='EBT_MOD_PROJECT_1', id=mod_id, name=name,
                    version=version, author=author, entries=[]))
    return path


def add(path, exported, name, kind, entry_id='', *, identity=''):
    data = load(path)
    identity = entry_id or identity or uuid.uuid4().hex
    old = next((e for e in data['entries'] if e['id'] == identity), None)
    if entry_id and old is None:
        raise ValueError('Entry to update no longer exists')
    if old and old['kind'] != kind:
        raise ValueError('Update must use the same entry type')
    snapshot = uuid.uuid4().hex
    destination = Path(path).resolve().parent / 'snapshots' / snapshot
    shutil.copytree(exported, destination)
    entry = dict(id=identity, snapshot=snapshot, name=name, kind=kind,
                 enabled=True, updated=datetime.now(timezone.utc).isoformat())
    if old:
        data['entries'][data['entries'].index(old)] = entry
    else:
        data['entries'].append(entry)
    save(path, data)
    return destination


def adopt(directory):
    """Capture a standalone EBT export before publishing its project manifest."""
    root = Path(directory).resolve()
    path = root / 'project.json'
    if path.exists():
        raise ValueError('A project file already exists; it will not be overwritten')
    metadata = json.loads((root / 'mod.json').read_text(encoding='utf-8-sig'))
    mod_id = metadata['id']
    if not re.fullmatch(r'[a-z0-9][a-z0-9_-]*', mod_id) or root.name != mod_id:
        raise ValueError('Mod folder must match its valid Mod ID')
    validation = json.loads((root / 'validation.json').read_text(encoding='utf-8-sig'))
    script = (root / 'src' / 'mod.lua').read_text(encoding='utf-8-sig')
    if 'Generated by Enshrouded Blender Tools' not in script[:512]:
        raise ValueError('Only standalone BlenderTools exports can be adopted')
    payload = (root / 'render_data.bin').read_bytes()
    if len(payload) != validation['mesh_size'] or hashlib.sha256(payload).hexdigest() != validation['mesh_sha256']:
        raise ValueError('Mesh payload does not match validation.json')
    crafting = json.loads((root / 'crafting.json').read_text(encoding='utf-8-sig')) if (root / 'crafting.json').is_file() else {}
    kind = ('EQUIPMENT' if crafting.get('equipment') else 'PLACEABLE') if validation['new_model'] else 'REPLACEMENT'
    name = validation.get('item_name') or validation.get('model_name') or metadata.get('name', mod_id)
    identity, snapshot = uuid.uuid4().hex, uuid.uuid4().hex
    destination = root / 'snapshots' / snapshot
    if any(p.is_symlink() for p in root.rglob('*')):
        raise ValueError('Mod contains symbolic links; adoption aborted')
    # Stage outside the source to avoid recursively copying snapshots into themselves.
    with tempfile.TemporaryDirectory(prefix='ebt_adopt_') as temp:
        staged = Path(temp) / 'export'
        shutil.copytree(root, staged, ignore=shutil.ignore_patterns('snapshots', 'project.json', '.incoming_*'))
        shutil.copytree(staged, destination)
    authors = metadata.get('authors') or ['Unknown']
    data = dict(format='EBT_MOD_PROJECT_1', id=mod_id, name=metadata.get('name', mod_id),
                version=metadata.get('version', '0.1.0'), author=', '.join(authors),
                entries=[dict(id=identity, snapshot=snapshot, name=name, kind=kind,
                              enabled=True, updated=datetime.now(timezone.utc).isoformat())])
    save(path, data)
    return path


def build(path, output, *, metadata=None):
    data = load(path)
    if metadata:
        data.update({key: metadata[key] for key in ('name', 'version', 'author')})
    entries = [e for e in data['entries'] if e['enabled']]
    if not entries:
        raise ValueError('Add or enable at least one export')
    root = Path(path).resolve().parent
    # Reject ambiguous overrides instead of silently applying last-writer wins.
    targets = set()
    all_targets = []
    sources = []
    for entry in entries:
        folder = root / 'snapshots' / entry['snapshot']
        validation = json.loads((folder / 'validation.json').read_text())
        all_targets.append(validation['target_guid'])
        if not validation['new_model']:
            target = validation['target_guid']
            if target in targets:
                raise ValueError('Two replacements override the same model: ' + target)
            targets.add(target)
        sources.append((entry, folder))
    if any(all_targets.count(target) > 1 for target in targets):
        raise ValueError('A replacement conflicts with another entry using the same base model')
    # Every build is recoverable; never overwrite a installed/user-created mod.
    destination = Path(output).resolve() / (data['id'] + '_build_' + uuid.uuid4().hex[:8])
    destination.mkdir(parents=True, exist_ok=False)
    (destination / 'src').mkdir()
    chunks = ['''-- Shared access to content created earlier in this mod build.
-- EML get_content may only resolve archive content, not newly created overrides.
local native_game = game
local created_content = {}
local shared_assets = setmetatable({}, {__index = native_game.assets})
shared_assets.create_content = function(payload)
    local content = native_game.assets.create_content(payload)
    if content ~= nil then
        local key = tostring(native_game.guid.from_content_hash(
            native_game.guid.to_content_hash(content.guid)))
        -- Keep both the content handle and serialized bytes alive across entries.
        created_content[key] = {handle = content, read_data = function() return payload end}
    end
    return content
end
shared_assets.get_content = function(guid)
    local cached = created_content[tostring(guid)]
    if cached ~= nil then return cached end
    return native_game.assets.get_content(guid)
end
local game = setmetatable({assets = shared_assets}, {__index = native_game});
''']
    for entry, folder in sources:
        prefix = 'entries/' + entry['id'] + '/'
        shutil.copytree(folder, destination / prefix,
                        ignore=shutil.ignore_patterns('mod.json', 'crafting.json'))
        code = (folder / 'src' / 'mod.lua').read_text(encoding='utf-8')
        # Upgrade stored exports: type enumeration omits newly created registries.
        old_registry_loop = 'for _, registry in ipairs(game.assets.get_resources_by_type("keen::RecipeRegistryResource")) do'
        if 'local active_recipe_registries = {}' in code:
            code = code.replace(old_registry_loop,
                'for registry_guid in pairs(active_recipe_registries) do\n'
                '    local registry = game.assets.get_resource(registry_guid, "keen::RecipeRegistryResource", 0)\n'
                '    if registry == nil then error("Active recipe registry not found: " .. registry_guid) end')
        # EML io.read is mod-relative. Scope a read adapter per entry, without
        # touching the global io table or sharing Lua locals between exports.
        chunks.append('(function()\nlocal project_io = io\nlocal io = setmetatable({read = function(path) return project_io.read("'
                      + prefix + '" .. path) end}, {__index = project_io})\n'
                      + code + '\nend)();\n')
    (destination / 'src' / 'mod.lua').write_text('\n'.join(chunks), encoding='utf-8')
    metadata = dict(id=data['id'], name=data['name'], version=data['version'],
                    authors=[data['author']], capabilities=['patch'],
                    description='Built with Enshrouded Blender Tools')
    (destination / 'mod.json').write_text(json.dumps(metadata, indent=2), encoding='utf-8')
    return destination


def build_installed(path, mods_root, metadata):
    """Stage first, then replace only owned build paths with rollback backups."""
    path = Path(path).resolve()
    target = path.parent
    mods_root = Path(mods_root).resolve()
    if target.parent != mods_root:
        raise ValueError('Select a project directly inside the game mods folder')
    data = load(path)
    if target.name != data['id']:
        raise ValueError('Project folder must match its Mod ID')
    names = ('src', 'entries', 'mod.json')
    for name in names:
        if (target / name).is_symlink() or (target / name).resolve().parent != target:
            raise ValueError('Unsafe build destination: ' + name)
    with tempfile.TemporaryDirectory(prefix='ebt_build_') as temp:
        staged = build(path, temp, metadata=metadata)
        backup = mods_root.parent / '.ebt-backups' / (data['id'] + '_' + uuid.uuid4().hex)
        backup.mkdir(parents=True)
        shutil.copy2(path, backup / 'project.json')
        moved, installed = [], []
        try:
            for name in names:
                dest = target / name
                if dest.exists():
                    dest.replace(backup / name)
                    moved.append(name)
                # Stage on the same volume before the final rename.
                incoming = target / ('.incoming_' + uuid.uuid4().hex)
                if (staged / name).is_dir():
                    shutil.copytree(staged / name, incoming)
                else:
                    shutil.copy2(staged / name, incoming)
                incoming.replace(dest)
                installed.append(name)
            data.update({key: metadata[key] for key in ('name', 'version', 'author')})
            save(path, data)
        except Exception:
            for name in reversed(installed):
                (target / name).replace(backup / ('failed_' + name))
            for name in moved:
                (backup / name).replace(target / name)
            raise
    return target
